spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false

logging:
  level:
    root: INFO
    com.cnctoolkit.backend: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: OFF

